### ISSUE TITLE
opptViewer command not found.

### ISSUE THREAD

**Issue by EthanCodesss** [rdl-algorithm/oppt#5]
As shown in the title.

**Comment by familyoyjx** [comment]
You can try the "./opptViewer" and the readme may omit "./".

**Comment by hoergems** [comment]
Hi Ethan.

How did you install OPPT? If you installed it outside of a system folder, you have to navigate to the <install folder>/bin directory and execute ./opptViewer from there.

**Comment by EthanCodesss** [comment]
> Hi Ethan.
> 
> How did you install OPPT? If you installed it outside of a system folder, you have to navigate to the /bin directory and execute ./opptViewer from there.



> You can try the "./opptViewer" and the readme may omit "./".

Thank you for your suggestions, the problem has been solved.
